# Generated by Django 5.0.6 on 2024-06-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gastos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateField()),
                ('monto', models.IntegerField()),
                ('done', models.BooleanField(default=False)),
            ],
        ),
    ]
