# Generated by Django 5.0.6 on 2024-06-06 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gastosapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gastos',
            name='done',
        ),
    ]
